// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/greeter/greeter.proto

package greeter

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the user's name.
type HelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_proto_greeter_greeter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_greeter_greeter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_proto_greeter_greeter_proto_rawDescGZIP(), []int{0}
}

func (x *HelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// The response message containing the greetings
type HelloReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloReply) Reset() {
	*x = HelloReply{}
	mi := &file_proto_greeter_greeter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloReply) ProtoMessage() {}

func (x *HelloReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_greeter_greeter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloReply.ProtoReflect.Descriptor instead.
func (*HelloReply) Descriptor() ([]byte, []int) {
	return file_proto_greeter_greeter_proto_rawDescGZIP(), []int{1}
}

func (x *HelloReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CreateGreeterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGreeterRequest) Reset() {
	*x = CreateGreeterRequest{}
	mi := &file_proto_greeter_greeter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGreeterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGreeterRequest) ProtoMessage() {}

func (x *CreateGreeterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_greeter_greeter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGreeterRequest.ProtoReflect.Descriptor instead.
func (*CreateGreeterRequest) Descriptor() ([]byte, []int) {
	return file_proto_greeter_greeter_proto_rawDescGZIP(), []int{2}
}

type CreateGreeterReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGreeterReply) Reset() {
	*x = CreateGreeterReply{}
	mi := &file_proto_greeter_greeter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGreeterReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGreeterReply) ProtoMessage() {}

func (x *CreateGreeterReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_greeter_greeter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGreeterReply.ProtoReflect.Descriptor instead.
func (*CreateGreeterReply) Descriptor() ([]byte, []int) {
	return file_proto_greeter_greeter_proto_rawDescGZIP(), []int{3}
}

type UpdateGreeterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGreeterRequest) Reset() {
	*x = UpdateGreeterRequest{}
	mi := &file_proto_greeter_greeter_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGreeterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGreeterRequest) ProtoMessage() {}

func (x *UpdateGreeterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_greeter_greeter_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGreeterRequest.ProtoReflect.Descriptor instead.
func (*UpdateGreeterRequest) Descriptor() ([]byte, []int) {
	return file_proto_greeter_greeter_proto_rawDescGZIP(), []int{4}
}

type UpdateGreeterReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGreeterReply) Reset() {
	*x = UpdateGreeterReply{}
	mi := &file_proto_greeter_greeter_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGreeterReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGreeterReply) ProtoMessage() {}

func (x *UpdateGreeterReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_greeter_greeter_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGreeterReply.ProtoReflect.Descriptor instead.
func (*UpdateGreeterReply) Descriptor() ([]byte, []int) {
	return file_proto_greeter_greeter_proto_rawDescGZIP(), []int{5}
}

type DeleteGreeterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGreeterRequest) Reset() {
	*x = DeleteGreeterRequest{}
	mi := &file_proto_greeter_greeter_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGreeterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGreeterRequest) ProtoMessage() {}

func (x *DeleteGreeterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_greeter_greeter_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGreeterRequest.ProtoReflect.Descriptor instead.
func (*DeleteGreeterRequest) Descriptor() ([]byte, []int) {
	return file_proto_greeter_greeter_proto_rawDescGZIP(), []int{6}
}

type DeleteGreeterReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGreeterReply) Reset() {
	*x = DeleteGreeterReply{}
	mi := &file_proto_greeter_greeter_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGreeterReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGreeterReply) ProtoMessage() {}

func (x *DeleteGreeterReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_greeter_greeter_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGreeterReply.ProtoReflect.Descriptor instead.
func (*DeleteGreeterReply) Descriptor() ([]byte, []int) {
	return file_proto_greeter_greeter_proto_rawDescGZIP(), []int{7}
}

type GetGreeterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGreeterRequest) Reset() {
	*x = GetGreeterRequest{}
	mi := &file_proto_greeter_greeter_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGreeterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGreeterRequest) ProtoMessage() {}

func (x *GetGreeterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_greeter_greeter_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGreeterRequest.ProtoReflect.Descriptor instead.
func (*GetGreeterRequest) Descriptor() ([]byte, []int) {
	return file_proto_greeter_greeter_proto_rawDescGZIP(), []int{8}
}

type GetGreeterReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGreeterReply) Reset() {
	*x = GetGreeterReply{}
	mi := &file_proto_greeter_greeter_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGreeterReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGreeterReply) ProtoMessage() {}

func (x *GetGreeterReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_greeter_greeter_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGreeterReply.ProtoReflect.Descriptor instead.
func (*GetGreeterReply) Descriptor() ([]byte, []int) {
	return file_proto_greeter_greeter_proto_rawDescGZIP(), []int{9}
}

type ListGreeterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGreeterRequest) Reset() {
	*x = ListGreeterRequest{}
	mi := &file_proto_greeter_greeter_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGreeterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGreeterRequest) ProtoMessage() {}

func (x *ListGreeterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_greeter_greeter_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGreeterRequest.ProtoReflect.Descriptor instead.
func (*ListGreeterRequest) Descriptor() ([]byte, []int) {
	return file_proto_greeter_greeter_proto_rawDescGZIP(), []int{10}
}

type ListGreeterReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGreeterReply) Reset() {
	*x = ListGreeterReply{}
	mi := &file_proto_greeter_greeter_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGreeterReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGreeterReply) ProtoMessage() {}

func (x *ListGreeterReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_greeter_greeter_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGreeterReply.ProtoReflect.Descriptor instead.
func (*ListGreeterReply) Descriptor() ([]byte, []int) {
	return file_proto_greeter_greeter_proto_rawDescGZIP(), []int{11}
}

var File_proto_greeter_greeter_proto protoreflect.FileDescriptor

const file_proto_greeter_greeter_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/greeter/greeter.proto\x12\rproto.greeter\x1a\x1cgoogle/api/annotations.proto\"\"\n" +
	"\fHelloRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"&\n" +
	"\n" +
	"HelloReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x16\n" +
	"\x14CreateGreeterRequest\"\x14\n" +
	"\x12CreateGreeterReply\"\x16\n" +
	"\x14UpdateGreeterRequest\"\x14\n" +
	"\x12UpdateGreeterReply\"\x16\n" +
	"\x14DeleteGreeterRequest\"\x14\n" +
	"\x12DeleteGreeterReply\"\x13\n" +
	"\x11GetGreeterRequest\"\x11\n" +
	"\x0fGetGreeterReply\"\x14\n" +
	"\x12ListGreeterRequest\"\x12\n" +
	"\x10ListGreeterReply2\x97\x04\n" +
	"\aGreeter\x12W\n" +
	"\rCreateGreeter\x12#.proto.greeter.CreateGreeterRequest\x1a!.proto.greeter.CreateGreeterReply\x12W\n" +
	"\rUpdateGreeter\x12#.proto.greeter.UpdateGreeterRequest\x1a!.proto.greeter.UpdateGreeterReply\x12W\n" +
	"\rDeleteGreeter\x12#.proto.greeter.DeleteGreeterRequest\x1a!.proto.greeter.DeleteGreeterReply\x12N\n" +
	"\n" +
	"GetGreeter\x12 .proto.greeter.GetGreeterRequest\x1a\x1e.proto.greeter.GetGreeterReply\x12Q\n" +
	"\vListGreeter\x12!.proto.greeter.ListGreeterRequest\x1a\x1f.proto.greeter.ListGreeterReply\x12^\n" +
	"\bSayHello\x12\x1b.proto.greeter.HelloRequest\x1a\x19.proto.greeter.HelloReply\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/helloworld/{name}B6\n" +
	"\rproto.greeterP\x01Z#kratos-layout/proto/greeter;greeterb\x06proto3"

var (
	file_proto_greeter_greeter_proto_rawDescOnce sync.Once
	file_proto_greeter_greeter_proto_rawDescData []byte
)

func file_proto_greeter_greeter_proto_rawDescGZIP() []byte {
	file_proto_greeter_greeter_proto_rawDescOnce.Do(func() {
		file_proto_greeter_greeter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_greeter_greeter_proto_rawDesc), len(file_proto_greeter_greeter_proto_rawDesc)))
	})
	return file_proto_greeter_greeter_proto_rawDescData
}

var file_proto_greeter_greeter_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_greeter_greeter_proto_goTypes = []any{
	(*HelloRequest)(nil),         // 0: proto.greeter.HelloRequest
	(*HelloReply)(nil),           // 1: proto.greeter.HelloReply
	(*CreateGreeterRequest)(nil), // 2: proto.greeter.CreateGreeterRequest
	(*CreateGreeterReply)(nil),   // 3: proto.greeter.CreateGreeterReply
	(*UpdateGreeterRequest)(nil), // 4: proto.greeter.UpdateGreeterRequest
	(*UpdateGreeterReply)(nil),   // 5: proto.greeter.UpdateGreeterReply
	(*DeleteGreeterRequest)(nil), // 6: proto.greeter.DeleteGreeterRequest
	(*DeleteGreeterReply)(nil),   // 7: proto.greeter.DeleteGreeterReply
	(*GetGreeterRequest)(nil),    // 8: proto.greeter.GetGreeterRequest
	(*GetGreeterReply)(nil),      // 9: proto.greeter.GetGreeterReply
	(*ListGreeterRequest)(nil),   // 10: proto.greeter.ListGreeterRequest
	(*ListGreeterReply)(nil),     // 11: proto.greeter.ListGreeterReply
}
var file_proto_greeter_greeter_proto_depIdxs = []int32{
	2,  // 0: proto.greeter.Greeter.CreateGreeter:input_type -> proto.greeter.CreateGreeterRequest
	4,  // 1: proto.greeter.Greeter.UpdateGreeter:input_type -> proto.greeter.UpdateGreeterRequest
	6,  // 2: proto.greeter.Greeter.DeleteGreeter:input_type -> proto.greeter.DeleteGreeterRequest
	8,  // 3: proto.greeter.Greeter.GetGreeter:input_type -> proto.greeter.GetGreeterRequest
	10, // 4: proto.greeter.Greeter.ListGreeter:input_type -> proto.greeter.ListGreeterRequest
	0,  // 5: proto.greeter.Greeter.SayHello:input_type -> proto.greeter.HelloRequest
	3,  // 6: proto.greeter.Greeter.CreateGreeter:output_type -> proto.greeter.CreateGreeterReply
	5,  // 7: proto.greeter.Greeter.UpdateGreeter:output_type -> proto.greeter.UpdateGreeterReply
	7,  // 8: proto.greeter.Greeter.DeleteGreeter:output_type -> proto.greeter.DeleteGreeterReply
	9,  // 9: proto.greeter.Greeter.GetGreeter:output_type -> proto.greeter.GetGreeterReply
	11, // 10: proto.greeter.Greeter.ListGreeter:output_type -> proto.greeter.ListGreeterReply
	1,  // 11: proto.greeter.Greeter.SayHello:output_type -> proto.greeter.HelloReply
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_proto_greeter_greeter_proto_init() }
func file_proto_greeter_greeter_proto_init() {
	if File_proto_greeter_greeter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_greeter_greeter_proto_rawDesc), len(file_proto_greeter_greeter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_greeter_greeter_proto_goTypes,
		DependencyIndexes: file_proto_greeter_greeter_proto_depIdxs,
		MessageInfos:      file_proto_greeter_greeter_proto_msgTypes,
	}.Build()
	File_proto_greeter_greeter_proto = out.File
	file_proto_greeter_greeter_proto_goTypes = nil
	file_proto_greeter_greeter_proto_depIdxs = nil
}
